// <auto-generated />
namespace ShoppingSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedFK_ProductId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFK_ProductId));
        
        string IMigrationMetadata.Id
        {
            get { return "201807231318192_addedFK_ProductId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
