// <auto-generated />
namespace ShoppingSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrderHeader_AddedColumnStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderHeader_AddedColumnStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201807301429086_OrderHeader_AddedColumnStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
