// <auto-generated />
namespace ShoppingSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Init_LoginHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_LoginHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201901310736382_Init_LoginHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
